Update chewtils (fix queue), add missing intents
- Updated chewtils to 2.1 stable (fixes `java.lang.NoSuchMethodError: 'boolean net.dv8tion.jda.api.Permission.isVoice()'` when running queue command)

- Added missing intents to be able to read messages